import { Raleway } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import {ProvideContext} from "@/app/UseAuth";

const ralewaySans = Raleway({
  variable: "--font-raleway-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ralewaySans.variable} antialiased`}>
        <ProvideContext>{children}  </ProvideContext>
        <ToastContainer autoClose={2000} hideProgressBar />
      </body>
    </html>
  );
}
